### ISSUE TITLE
Missing Method Exception 

### ISSUE THREAD

**Issue by KyleC69** [ChromiumDotNet/PuppeteerSharp.Dom#1]
### Description

Exception is thrown System.MissingMethodException when attempting to use an extension method from puppeteersharp.dom

### Complete minimal example reproducing the issue

Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

E.g.

```csharp

 private static async Task Main(string[] args)
    {


        var fetcher = new BrowserFetcher();
        await fetcher.DownloadAsync();


        //using var browser = await Puppeteer.LaunchAsync(new LaunchOptions{ Headless = false, ExecutablePath=@"/Storage/Apps/Browser/chrome-linux64/chrome" });
        using (var browser = await Puppeteer.LaunchAsync(new LaunchOptions { Headless = false }))
        {
            using (var page = await browser.NewPageAsync())
            {
                browser.DefaultWaitForTimeout = 100000;
                page.DefaultNavigationTimeout = 100000;
                page.DefaultTimeout = 100000;

                await page.GoToAsync("https://googler.com/");



              //  await page.WaitForSelectorAsync(".vue-recycle-scroller__item-wrapper");

                //print height offset of scroller container
                var wrapper = await page.QuerySelectorAsync<HtmlElement>(".vue-recycle-scroller__item-wrapper");
                var sHeight = await wrapper.GetAttributeAsync("min-height");


                var divElements = await page.QuerySelectorAllAsync<HtmlDivElement>(".vue-recycle-scroller__item-view");

                foreach (var item in divElements)
                {
                    var idx = await item.QuerySelectorAsync<HtmlElement>("div");
                    var val = await idx.GetAttributeAsync<string>("data-index");
                    System.Console.WriteLine("Index: " + val);
                }
                await page.Keyboard.PressAsync("PageDown", new PuppeteerSharp.Input.PressOptions { Delay = 2000 });
            }
        }       

}

...
```

### Expected behaviour:

Methods should return elements expected.

### Actual behaviour:

With the extension method in the code the exception is thrown without even opening the browser. If I comment out the strongly typed extension method the code will run and open browser and complete any calls to standard puppeteersharp methods.

### Versions

puppeteersharp.dom 3.0.24
puppeteersharp  18.03  @@@@ downgraded and attempted with versions 13, 14 ,15, 16, 17 with the same results.
target framework Dotnet 8
Installed Sdk's 6, 8 and 9 preview 5

### Additional Information

Above code was run in a new console app from template, no settings were changed in project from default template.

**Comment by amaitland** [comment]
A new versions is now available.

https://www.nuget.org/packages/PuppeteerSharp.Dom/4.0.27
