### ISSUE TITLE
AsyncDomExtensions.AndThen null inputTask result handling consufion

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [ChromiumDotNet/PuppeteerSharp.Dom#3]
I was confused at first when try to chain QuerySelector and return desired value from it. Basically I did next
```
var strContent = await item.QuerySelectorAsync<HtmlDivElement>(".MyElement")
    .AndThen(x => x.GetTextContentAsync());
```
I was expecting that it will return result as method allow me to do this, but got exception [here](https://github.com/ChromiumDotNet/PuppeteerSharp.Dom/blob/32cca1b426fe6d07c253f9407b47bd5a7fbaeb8a/PuppeteerSharp.Dom/AsyncDomExtensions.cs#L165)
From description I can suggest that it was not intended to be used this way, but rather as kind of select chaining

But problem is that first of all it allows to write this code and if I didn't connect project directly in my solution and use nuget I would get error that doesnt explain what is happening and why.

And on other hand it can work as can be expected, but with irritating crutch
```
var strContent = await item.QuerySelectorAsync<HtmlDivElement>(".MyElement")
    .AndThen(x => x != null ? x.GetTextContentAsync() : Task.FromResult<string>(null!));
```

I think something is wrong with it but I myself can't quiet catch what it is because `x` is basically a `DomHandle` element and you should be able to work inside this function however you like but then it forces you to return Task as well or write async before every function adding overhead.

So main problem is that `AndThen` allows you to write code that throws in very appealing way and I'm not sure if it's a bug or a feature

**Comment by amaitland** [comment]
The two minor bugs with attempting to dispose if the returned handle was `null` should have been fixed in commit https://github.com/ChromiumDotNet/PuppeteerSharp.Dom/commit/65b380a6e4709a4d7c5579ddb5d30b7113763a9d and 
https://github.com/ChromiumDotNet/PuppeteerSharp.Dom/commit/534ef7812ff6d61a5fc92d5a70dd3569e6275eb8

Thanks!

**Comment by CaCTuCaTu4ECKuu** [comment]
> The two minor bugs with attempting to dispose if the returned handle was `null`

Good! So there was another one of those

Regarding issue I figured that I completely forgot one thing
```
var strContent = await item.QuerySelectorAsync<HtmlDivElement>(".MyElement")
    .AndThen(async x => x != null ? await x.GetTextContentAsync() : "");
```

Oh my god I already imagine this code
```
var strContent = await item.QuerySelectorAsync<HtmlDivElement>(".MyElement")
    .AndThen(async x => x != null ? await x.GetTextContentAsync().ConfigureAwait(false) : await SomeAsync().ConfigureAwait(false));
```
